'use client';

import Link from 'next/link'
import { usePathname } from 'next/navigation';
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const navLinks = [
  {
    name: "Home",
    href: "/"
  },
  {
    name: "dashboard",
    href: "/dashboard"
  },
  {
    name: "Settings",
    href: "/dashboard/settings"
  },
]

export default function RootLayout({ children }) {
  const pathname = usePathname();

  return (
    <html lang="en">
      <body>
      <nav>
      {navLinks.map((link) => {
          const active = pathname === link.href

          return <Link
           href={link.href}
           key={link.name}
           className={active ? `red` : `text-black`}
           >{link.name}</Link>
      }
      )}
        </nav>
      {children}
      <footer>Footer</footer>
      </body>
    </html>
  )
}
